/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crud;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author luiso
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFrame
     */
    public CadastroView() {
        initComponents();
        
        this.setResizable(false);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/logoEdamatecReduzido.png")));
        
        ImageIcon ImgLogoHeader = new ImageIcon(getClass().getResource("../img/logoEdamatecReduzido.png"));     
        Image ImgLogoHeaderEdit = ImgLogoHeader.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        labelLogoHeader.setIcon(new ImageIcon(ImgLogoHeaderEdit));
        
        ImageIcon ImgLogoFooter = new ImageIcon(getClass().getResource("../img/logo_edamatec.png"));     
        Image ImgLogoFooterEdit = ImgLogoFooter.getImage().getScaledInstance(187, 60, Image.SCALE_DEFAULT);
        labelLogoFooter.setIcon(new ImageIcon(ImgLogoFooterEdit));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBackgroundArea = new javax.swing.JPanel();
        painelHheaderArea = new javax.swing.JPanel();
        labelLogoHeader = new javax.swing.JLabel();
        labelTitlteHeader = new javax.swing.JLabel();
        painelCreateArea = new javax.swing.JPanel();
        labelNomeCreateArea = new javax.swing.JLabel();
        fieldNomeCreateArea = new javax.swing.JTextField();
        labelCpfCreateArea = new javax.swing.JLabel();
        fieldCpfCreateArea = new javax.swing.JTextField();
        labelTelefoneCreateArea = new javax.swing.JLabel();
        fieldTelefoneCreateArea = new javax.swing.JTextField();
        labelEmailCreateArea = new javax.swing.JLabel();
        fieldEmailCreateArea = new javax.swing.JTextField();
        labelSenhaCreateArea = new javax.swing.JLabel();
        fieldSenhaCreateArea = new javax.swing.JPasswordField();
        buttonCadastrarCreateArea = new javax.swing.JButton();
        buttonVoltarCreateArea = new javax.swing.JButton();
        painelFooterArea = new javax.swing.JPanel();
        labelLogoFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelBackgroundArea.setBackground(new java.awt.Color(255, 255, 255));
        painelBackgroundArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelHheaderArea.setBackground(new java.awt.Color(0, 0, 204));
        painelHheaderArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogoHeader.setMaximumSize(new java.awt.Dimension(709, 681));
        painelHheaderArea.add(labelLogoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 17, 60, 60));

        labelTitlteHeader.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitlteHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelTitlteHeader.setText("CRUD App");
        painelHheaderArea.add(labelTitlteHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 17, 460, 60));

        painelBackgroundArea.add(painelHheaderArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 94));

        painelCreateArea.setBackground(new java.awt.Color(255, 255, 255));
        painelCreateArea.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true), "CADASTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCreateArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNomeCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelNomeCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNomeCreateArea.setText("Nome:");
        painelCreateArea.add(labelNomeCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 67, 107, 28));
        painelCreateArea.add(fieldNomeCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 66, 300, 30));

        labelCpfCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCpfCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelCpfCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCpfCreateArea.setText("CPF:");
        painelCreateArea.add(labelCpfCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 115, 62, 28));
        painelCreateArea.add(fieldCpfCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 114, 300, 30));

        labelTelefoneCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTelefoneCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelTelefoneCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTelefoneCreateArea.setText("Telefone:");
        painelCreateArea.add(labelTelefoneCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 163, -1, 28));
        painelCreateArea.add(fieldTelefoneCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 162, 300, 30));

        labelEmailCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEmailCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelEmailCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmailCreateArea.setText("Email:");
        painelCreateArea.add(labelEmailCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 211, 62, 28));
        painelCreateArea.add(fieldEmailCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 210, 300, 30));

        labelSenhaCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSenhaCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelSenhaCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSenhaCreateArea.setText("Senha:");
        painelCreateArea.add(labelSenhaCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 261, -1, -1));
        painelCreateArea.add(fieldSenhaCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 258, 300, 30));

        buttonCadastrarCreateArea.setBackground(new java.awt.Color(0, 0, 204));
        buttonCadastrarCreateArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCadastrarCreateArea.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastrarCreateArea.setText("Cadastrar");
        buttonCadastrarCreateArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarCreateAreaActionPerformed(evt);
            }
        });
        painelCreateArea.add(buttonCadastrarCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 323, 140, 41));

        buttonVoltarCreateArea.setBackground(new java.awt.Color(255, 0, 51));
        buttonVoltarCreateArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonVoltarCreateArea.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltarCreateArea.setText("Voltar");
        buttonVoltarCreateArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarCreateAreaActionPerformed(evt);
            }
        });
        painelCreateArea.add(buttonVoltarCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 323, 140, 41));

        painelBackgroundArea.add(painelCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 440));

        painelFooterArea.setBackground(new java.awt.Color(255, 255, 255));
        painelFooterArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelFooterArea.add(labelLogoFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 23, 240, 70));

        painelBackgroundArea.add(painelFooterArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 630, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackgroundArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackgroundArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarCreateAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarCreateAreaActionPerformed
        String nome = fieldNomeCreateArea.getText();
        String cpf = fieldCpfCreateArea.getText();
        String telefone = fieldTelefoneCreateArea.getText();
        String email = fieldEmailCreateArea.getText();
        String senha = fieldSenhaCreateArea.getText();
        
        Bean beanObj = new Bean(nome, cpf, telefone, email, senha);
        
        CadastroModel balObj = new CadastroModel();
        balObj.cadastrarUsuario(beanObj);
        
        this.hide();
        LoginView loginObj = new LoginView();
        loginObj.show();
    }//GEN-LAST:event_buttonCadastrarCreateAreaActionPerformed

    private void buttonVoltarCreateAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarCreateAreaActionPerformed
        this.hide();
        LoginView loginObj = new LoginView();
        loginObj.show();
    }//GEN-LAST:event_buttonVoltarCreateAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarCreateArea;
    private javax.swing.JButton buttonVoltarCreateArea;
    private javax.swing.JTextField fieldCpfCreateArea;
    private javax.swing.JTextField fieldEmailCreateArea;
    private javax.swing.JTextField fieldNomeCreateArea;
    private javax.swing.JPasswordField fieldSenhaCreateArea;
    private javax.swing.JTextField fieldTelefoneCreateArea;
    private javax.swing.JLabel labelCpfCreateArea;
    private javax.swing.JLabel labelEmailCreateArea;
    private javax.swing.JLabel labelLogoFooter;
    private javax.swing.JLabel labelLogoHeader;
    private javax.swing.JLabel labelNomeCreateArea;
    private javax.swing.JLabel labelSenhaCreateArea;
    private javax.swing.JLabel labelTelefoneCreateArea;
    private javax.swing.JLabel labelTitlteHeader;
    private javax.swing.JPanel painelBackgroundArea;
    private javax.swing.JPanel painelCreateArea;
    private javax.swing.JPanel painelFooterArea;
    private javax.swing.JPanel painelHheaderArea;
    // End of variables declaration//GEN-END:variables
}
