/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crud;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiso
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    int id = 0;

    public HomeView() {
        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/logoEdamatecReduzido.png")));

        ImageIcon ImgLogoHeader = new ImageIcon(getClass().getResource("../img/logoEdamatecReduzido.png"));
        Image ImgLogoHeaderEdit = ImgLogoHeader.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        labelLogoHeader.setIcon(new ImageIcon(ImgLogoHeaderEdit));

        ImageIcon ImgLogoFooter = new ImageIcon(getClass().getResource("../img/logo_edamatec.png"));
        Image ImgLogoFooterEdit = ImgLogoFooter.getImage().getScaledInstance(187, 60, Image.SCALE_DEFAULT);
        labelLogoFooter.setIcon(new ImageIcon(ImgLogoFooterEdit));

        criarTabela();
    }

    public void carregarTabela(List<Bean> list) {
        DefaultTableModel tabela = (DefaultTableModel) table.getModel();
        tabela.setRowCount(0);

        for (Bean bean : list) {
            Vector vetor = new Vector();
            vetor.add(bean.getId());
            vetor.add(bean.getNome());
            vetor.add(bean.getCpf());
            vetor.add(bean.getTelefone());
            vetor.add(bean.getEmail());

            tabela.addRow(vetor);
        }
    }

    public void criarTabela() {
        HomeModel model = new HomeModel();
        List list = model.loadData();
        carregarTabela(list);
    }

    public void limparCampos() {
        fieldNomeCreateArea.setText("");
        fieldCpfCreateArea.setText("");
        fieldTelefoneCreateArea.setText("");
        fieldEmailCreateArea.setText("");
        fieldSenhaCreateArea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelHheaderArea = new javax.swing.JPanel();
        labelLogoHeader = new javax.swing.JLabel();
        labelTitlteHeader1 = new javax.swing.JLabel();
        painelCreateArea = new javax.swing.JPanel();
        labelNomeCreateArea = new javax.swing.JLabel();
        fieldNomeCreateArea = new javax.swing.JTextField();
        labelCpfCreateArea = new javax.swing.JLabel();
        fieldCpfCreateArea = new javax.swing.JTextField();
        labelTelefoneCreateArea = new javax.swing.JLabel();
        fieldTelefoneCreateArea = new javax.swing.JTextField();
        labelEmailCreateArea = new javax.swing.JLabel();
        fieldEmailCreateArea = new javax.swing.JTextField();
        labelSenhaCreateArea = new javax.swing.JLabel();
        fieldSenhaCreateArea = new javax.swing.JPasswordField();
        buttonInserir = new javax.swing.JButton();
        buttonAtualizar = new javax.swing.JButton();
        buttonDeletar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        labelInfo = new javax.swing.JLabel();
        painelFooterArea = new javax.swing.JPanel();
        labelLogoFooter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelHheaderArea.setBackground(new java.awt.Color(0, 0, 204));
        painelHheaderArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogoHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logoEdamatecReduzido.png"))); // NOI18N
        labelLogoHeader.setMaximumSize(new java.awt.Dimension(709, 681));
        painelHheaderArea.add(labelLogoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 17, 60, 60));

        labelTitlteHeader1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitlteHeader1.setForeground(new java.awt.Color(255, 255, 255));
        labelTitlteHeader1.setText("CRUD App");
        painelHheaderArea.add(labelTitlteHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 17, 460, 60));

        jPanel1.add(painelHheaderArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 94));

        painelCreateArea.setBackground(new java.awt.Color(255, 255, 255));
        painelCreateArea.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true), "PAINEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCreateArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNomeCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelNomeCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNomeCreateArea.setText("Nome:");
        painelCreateArea.add(labelNomeCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 67, 107, 28));
        painelCreateArea.add(fieldNomeCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 66, 300, 30));

        labelCpfCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCpfCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelCpfCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCpfCreateArea.setText("CPF:");
        painelCreateArea.add(labelCpfCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 115, 62, 28));
        painelCreateArea.add(fieldCpfCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 114, 300, 30));

        labelTelefoneCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTelefoneCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelTelefoneCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTelefoneCreateArea.setText("Telefone:");
        painelCreateArea.add(labelTelefoneCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 163, -1, 28));
        painelCreateArea.add(fieldTelefoneCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 162, 300, 30));

        labelEmailCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEmailCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelEmailCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEmailCreateArea.setText("Email:");
        painelCreateArea.add(labelEmailCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 211, 62, 28));
        painelCreateArea.add(fieldEmailCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 210, 300, 30));

        labelSenhaCreateArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSenhaCreateArea.setForeground(new java.awt.Color(0, 0, 204));
        labelSenhaCreateArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSenhaCreateArea.setText("Senha:");
        painelCreateArea.add(labelSenhaCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 261, -1, -1));
        painelCreateArea.add(fieldSenhaCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 258, 300, 30));

        buttonInserir.setBackground(new java.awt.Color(0, 0, 204));
        buttonInserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonInserir.setForeground(new java.awt.Color(255, 255, 255));
        buttonInserir.setText("Inserir");
        buttonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirActionPerformed(evt);
            }
        });
        painelCreateArea.add(buttonInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 323, 140, 41));

        buttonAtualizar.setBackground(new java.awt.Color(51, 204, 0));
        buttonAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAtualizar.setText("Atualizar");
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });
        painelCreateArea.add(buttonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 323, 140, 41));

        buttonDeletar.setBackground(new java.awt.Color(255, 0, 51));
        buttonDeletar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonDeletar.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeletar.setText("Deletar");
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });
        painelCreateArea.add(buttonDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 140, 41));

        buttonLimpar.setBackground(new java.awt.Color(255, 255, 255));
        buttonLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonLimpar.setForeground(new java.awt.Color(0, 0, 255));
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });
        painelCreateArea.add(buttonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 140, 41));

        labelInfo.setText("Para atualizar ou deletar, selecione o usuário na tabela.");
        painelCreateArea.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jPanel1.add(painelCreateArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 610, 480));

        painelFooterArea.setBackground(new java.awt.Color(255, 255, 255));
        painelFooterArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogoFooter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo_edamatec.png"))); // NOI18N
        painelFooterArea.add(labelLogoFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 240, 70));

        jPanel1.add(painelFooterArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1366, 170));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 730, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirActionPerformed
        String nome = fieldNomeCreateArea.getText();
        String cpf = fieldCpfCreateArea.getText();
        String telefone = fieldTelefoneCreateArea.getText();
        String email = fieldEmailCreateArea.getText();
        String senha = fieldSenhaCreateArea.getText();

        Bean beanObj = new Bean(0, nome, cpf, telefone, email, senha);

        HomeModel balObj = new HomeModel();
        balObj.cadastrarUsuario(beanObj);
        criarTabela();
    }//GEN-LAST:event_buttonInserirActionPerformed

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarActionPerformed
        String nome = fieldNomeCreateArea.getText();
        String cpf = fieldCpfCreateArea.getText();
        String telefone = fieldTelefoneCreateArea.getText();
        String email = fieldEmailCreateArea.getText();
        String senha = fieldSenhaCreateArea.getText();
        Bean bean = new Bean(id, nome, cpf, telefone, email, senha);
        HomeModel model = new HomeModel();
        model.atualizarUsuario(bean);
        criarTabela();
    }//GEN-LAST:event_buttonAtualizarActionPerformed

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarActionPerformed
        HomeModel model = new HomeModel();
        model.deletarUsuario(id);
        criarTabela();
    }//GEN-LAST:event_buttonDeletarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int row = table.getSelectedRow();

        if (row < 0) {
            JoptionPanel.showMessageDialog(null, "Por favor selecione qualquer resgtiro da tabela para atualizar");
        } else {
            id = (int) table.getValueAt(row, 0);
            HomeModel model = new HomeModel();
            Bean bean = model.retornarDados(id);
            fieldNomeCreateArea.setText(bean.getNome());
            fieldCpfCreateArea.setText(bean.getCpf());
            fieldTelefoneCreateArea.setText(bean.getTelefone());
            fieldEmailCreateArea.setText(bean.getEmail());
            fieldSenhaCreateArea.setText(bean.getSenha());
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JButton buttonInserir;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JTextField fieldCpfCreateArea;
    private javax.swing.JTextField fieldEmailCreateArea;
    private javax.swing.JTextField fieldNomeCreateArea;
    private javax.swing.JPasswordField fieldSenhaCreateArea;
    private javax.swing.JTextField fieldTelefoneCreateArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCpfCreateArea;
    private javax.swing.JLabel labelEmailCreateArea;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelLogoFooter;
    private javax.swing.JLabel labelLogoHeader;
    private javax.swing.JLabel labelNomeCreateArea;
    private javax.swing.JLabel labelSenhaCreateArea;
    private javax.swing.JLabel labelTelefoneCreateArea;
    private javax.swing.JLabel labelTitlteHeader1;
    private javax.swing.JPanel painelCreateArea;
    private javax.swing.JPanel painelFooterArea;
    private javax.swing.JPanel painelHheaderArea;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private static class JoptionPanel {

        private static void showMessageDialog(Object object, String por_favor_selecione_qualquer_resgtiro_da_) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public JoptionPanel() {
        }
    }
}
