/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crud;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author luiso
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginView() {
        initComponents();

        this.setResizable(false);

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/logoEdamatecReduzido.png")));

        ImageIcon ImgLogoHeader = new ImageIcon(getClass().getResource("../img/logoEdamatecReduzido.png"));
        Image ImgLogoHeaderEdit = ImgLogoHeader.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        labelLogoHeader.setIcon(new ImageIcon(ImgLogoHeaderEdit));

        ImageIcon ImgLogoFooter = new ImageIcon(getClass().getResource("../img/logo_edamatec.png"));
        Image ImgLogoFooterEdit = ImgLogoFooter.getImage().getScaledInstance(187, 60, Image.SCALE_DEFAULT);
        labelLogoFooter.setIcon(new ImageIcon(ImgLogoFooterEdit));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBackgroundArea = new javax.swing.JPanel();
        painelHheaderArea = new javax.swing.JPanel();
        labelLogoHeader = new javax.swing.JLabel();
        labelTitlteHeader = new javax.swing.JLabel();
        painelLoginArea = new javax.swing.JPanel();
        labelEmailLoginArea = new javax.swing.JLabel();
        fieldEmailLoginArea = new javax.swing.JTextField();
        labelSenhaLoginArea = new javax.swing.JLabel();
        fieldSenhaLoginArea = new javax.swing.JPasswordField();
        buttonEntrarLoginArea = new javax.swing.JButton();
        buttonCadastrarLoginArea = new javax.swing.JButton();
        painelFooterArea = new javax.swing.JPanel();
        labelLogoFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelBackgroundArea.setBackground(new java.awt.Color(255, 255, 255));
        painelBackgroundArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelHheaderArea.setBackground(new java.awt.Color(0, 0, 204));
        painelHheaderArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogoHeader.setMaximumSize(new java.awt.Dimension(709, 681));
        painelHheaderArea.add(labelLogoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 17, 60, 60));

        labelTitlteHeader.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitlteHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelTitlteHeader.setText("CRUD App");
        painelHheaderArea.add(labelTitlteHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 17, 460, 60));

        painelBackgroundArea.add(painelHheaderArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 100));

        painelLoginArea.setBackground(new java.awt.Color(255, 255, 255));
        painelLoginArea.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true), "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        painelLoginArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmailLoginArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEmailLoginArea.setForeground(new java.awt.Color(0, 0, 204));
        labelEmailLoginArea.setText("Email:");
        painelLoginArea.add(labelEmailLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 70, 62, 28));
        painelLoginArea.add(fieldEmailLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 69, 300, 30));

        labelSenhaLoginArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSenhaLoginArea.setForeground(new java.awt.Color(0, 0, 204));
        labelSenhaLoginArea.setText("Senha:");
        painelLoginArea.add(labelSenhaLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 120, -1, -1));
        painelLoginArea.add(fieldSenhaLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 117, 300, 30));

        buttonEntrarLoginArea.setBackground(new java.awt.Color(0, 0, 204));
        buttonEntrarLoginArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonEntrarLoginArea.setForeground(new java.awt.Color(255, 255, 255));
        buttonEntrarLoginArea.setText("Entrar");
        buttonEntrarLoginArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarLoginAreaActionPerformed(evt);
            }
        });
        painelLoginArea.add(buttonEntrarLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 185, 152, 41));

        buttonCadastrarLoginArea.setBackground(new java.awt.Color(0, 0, 204));
        buttonCadastrarLoginArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCadastrarLoginArea.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastrarLoginArea.setText("Cadastrar");
        buttonCadastrarLoginArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarLoginAreaActionPerformed(evt);
            }
        });
        painelLoginArea.add(buttonCadastrarLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 237, 152, 41));

        painelBackgroundArea.add(painelLoginArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 440));

        painelFooterArea.setBackground(new java.awt.Color(255, 255, 255));
        painelFooterArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelFooterArea.add(labelLogoFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 23, 240, 70));

        painelBackgroundArea.add(painelFooterArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 630, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackgroundArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackgroundArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarLoginAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarLoginAreaActionPerformed
        this.hide();
        CadastroView cadastroObj = new CadastroView();
        cadastroObj.show();
    }//GEN-LAST:event_buttonCadastrarLoginAreaActionPerformed

    private void buttonEntrarLoginAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarLoginAreaActionPerformed
        String email = fieldEmailLoginArea.getText();
        String senha = fieldSenhaLoginArea.getText();
        
        LoginModel balObj = new LoginModel();
        boolean b = balObj.verificarLogin(email, senha);
        
        if (b) {
            this.hide();
            HomeView homeObj = new HomeView();
            homeObj.show();
                  
        
        }
    }//GEN-LAST:event_buttonEntrarLoginAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarLoginArea;
    private javax.swing.JButton buttonEntrarLoginArea;
    private javax.swing.JTextField fieldEmailLoginArea;
    private javax.swing.JPasswordField fieldSenhaLoginArea;
    private javax.swing.JLabel labelEmailLoginArea;
    private javax.swing.JLabel labelLogoFooter;
    private javax.swing.JLabel labelLogoHeader;
    private javax.swing.JLabel labelSenhaLoginArea;
    private javax.swing.JLabel labelTitlteHeader;
    private javax.swing.JPanel painelBackgroundArea;
    private javax.swing.JPanel painelFooterArea;
    private javax.swing.JPanel painelHheaderArea;
    private javax.swing.JPanel painelLoginArea;
    // End of variables declaration//GEN-END:variables
}
